### ISSUE TITLE
clashing class names and outdated npm?

### ISSUE THREAD

**Issue by EhsanKia** [shama/view-list#7]
Two issues when I tried using this.

First off, .bottom and .top are way too generic and easily clash with other CSS on the page (in my case, I'm making an extension and can't modify the CSS on the page). Maybe make them customizable through the config?

Secondly, is the npm version outdated? It didn't have the last commit which added 'px'. Or maybe you need to bump the version? I've never put stuff on npm so I'm not sure how it works.

**Comment by shama** [comment]
1. We could totally make it customizable. 2. Yep! It looks like I didn't bump the last change. Thanks for the heads up!

**Comment by shama** [comment]
Fixed by #8
